### ISSUE TITLE
try-convert still rejecting projects that reference System.Web

### ISSUE THREAD

**Issue by MaherJendoubi** [dotnet/try-convert#286]
Hello,
I am using version 0.4.125402 for try-convert and still having rejection of projects that reference System.Web : 

λ **try-convert -w ImageViewer.sln**
C:\Users\xxx\Documents\GitHub\ClearCanvas\Common\ClearCanvas.Common.csproj contains a reference to System.Web, which is not supported on .NET Core. You may have significant work ahead of you to fully port this project.
System.IO.IOException: The file 'C:\Users\xxx\Documents\GitHub\ClearCanvas\Common\ClearCanvas.Common.csproj.old' already exists.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at MSBuild.Abstractions.MSBuildWorkspace..ctor(ImmutableArray`1 paths, Boolean noBackup) in /_/src/MSBuild.Abstractions/MSBuildWorkspace.cs:line 41
   at MSBuild.Abstractions.MSBuildWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup) in /_/src/MSBuild.Abstractions/MSBuildWorkspaceLoader.cs:line 45
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, String tfm, Boolean allowPreviews, Boolean diffOnly, Boolean noBackup) in /_/src/try-convert/Program.cs:line 93

**Comment by cartermp** [comment]
@MaherJendoubi The issue you're seeing isn't that it rejects the project, but that it fails to write the `.old` backup because you already have one there. I think we can just fix this to overwrite whatever `.old` file lives there, since this just crashes the tool today

**Comment by MaherJendoubi** [comment]
@cartermp Thanks a lot for your reply.
I updated try-convert but the problem remains. I even deleted manually the.old file but in vain.
Any idea?

**Comment by MaherJendoubi** [comment]
![image](https://user-images.githubusercontent.com/1798510/81216316-01db9900-8fdb-11ea-844d-3fe500698d50.png)

**Comment by cartermp** [comment]
Without seeing your project, there's no way to tell. However, if it's an old MVC project then I don't think it will ever support conversion. Even if the project file could be brought to a good place, you'd have to completely rewrite your application since none of the old ASP.NET APIs exist on .NET Core.

**Comment by MaherJendoubi** [comment]
@cartermp The project is open-source https://github.com/ClearCanvas/ClearCanvas

**Comment by cartermp** [comment]
@MaherJendoubi Thanks. This error happens when you have nonstandard imports. There's no telling what kinds of targets are getting loaded and if they're compatible with .NET Core, so the tool rejects projects when it sees this. It does mean that even if the targets are runnable on .NET Core, the project gets rejected. This might be something that can be handled more intricately, but since you can specify pretty much anything in a target we take the safe route and just actively reject it.

**Comment by MaherJendoubi** [comment]
@cartermp Thanks for this precious feedback. I wonder if you could recommend me what should I do to tackle this migration problem. Would you please be more specific about the nonstandard imports?
