### ISSUE TITLE
Project not converting : xx.csproj contains a reference to System.Web

### ISSUE THREAD

**Issue by MilindThakkar** [dotnet/try-convert#289]
Hi,
I am trying to convert a .Net 4.6.1 MVC website project to core, its giving following errors:

> xx.csproj contains a reference to System.Web, which is not supported on .NET Core. You may have significant work ahead of you to fully port this project.
'xx.csproj' is a legacy web project and/or reference System.Web. Legacy Web projects and System.Web are unsupported on .NET Core. You will need to rewrite your application or find a way to not depend on System.Web to convert this project.
'yy.csproj' is already a .NET SDK-style project, so it won't be converted.

> 
It doesn't change anything at all. For confirmation, I am using command _try-convert -w "MyWeb.sln"_
Am I missing something or is this expected behavior. What should be the next steps?

Thanks
Milind

**Comment by cartermp** [comment]
@MilindThakkar In the error message, you'll see that the tool already detected that your project is an SDK-style project, so it won't be converted. This isn't related to referencing System.Web.

**Comment by MilindThakkar** [comment]
@cartermp There are two projects in the solution: one is MVC application xx.csproj and other is a library yy.csprj.

First issue is: For MVC application it's giving issue with system.web. 

Second: For library, though it's targeting .Net Framework 4.6.1, it's suggesting "already a .NET SDK-style project, so it won't be converted". Shouldn't it re-target it to .Net Core?

Hope that gives better clarity.

**Comment by cartermp** [comment]
@MilindThakkar For the first issue, this is expected. We notify about `System.Web` in the tool specifically because it's completely incompatible with .NET Core. You'll need to rewrite anything that depends on it.

For the second issue, if it's already SDK-style, the tool has nothing to really do. We don't always retarget to .NET Core. The logic for picking an appropriate TFM is actually fairly involved: https://github.com/dotnet/try-convert/blob/master/src/MSBuild.Conversion.Project/Converter.cs#L55

The primary goal of this tool is to just get your project files into a reasonable state (that will load in VS) so that you can focus more about APIs and code when moving to .NET Core. There's some things that can be automated further, like explicitly targeting .NET Core for a winforms or wpf app by default, since we can know ahead of time that such an action is generally safe. But that may not necessarily be true for an arbitrary library project. A new version of the tool will default libraries to .NET Standard.

However, if your project is already SDK-style, then it's already pretty much in the state that the tool would get you to. We don't really intent on supporting the simplification of existing SDK-style projects.

**Comment by ChrisBertrand** [comment]
I'm getting a similar error. Minus the SDK bit. Can a conversion occur or is this a manual process now copying controllers, views, packages and dependencies across?

**Comment by cartermp** [comment]
@ChrisBertrand Are you using the latest version of the tool?

Separately, there is no automated conversion that can be done for System.Web and old-style web projects. This is why the tool warns about System.Web and rejects old-style web projects. It is a full-scale rewrite of that part of your application since all of the APIs are different.

**Comment by ChrisBertrand** [comment]
Yes, on version '0.5.125603'

The full error states:

C:\Projects\Web.csproj contains a reference to System.Web, which is not supported on .NET Core. You may have significant work ahead of you to fully port this project.
'C:\Projects\Web.csproj' is a legacy web project and/or reference System.Web. Legacy Web projects and System.Web are unsupported on .NET Core. You will need to rewrite your application or find a way to not depend on System.Web to convert this project.
Conversion complete!

What would you suggest to do, as there are a number of dependencies to System.Web. I'm not sure if it's an old style project. It's a Framework 4.7.2 MVC Project.

**Comment by cartermp** [comment]
Thanks @ChrisBertrand . The first thing to note here is that this isn't an error, but a warning. You'll see that the conversion actually did run, but since you're referencing System.Web the tool lets you know that this reference will not work on .NET Core. So this is one task to perform to ultimately get there. It's not possible to convert to some different reference, since all of the APIs on .NET Core for doing web stuff are different.

Separately, this is even more incompatible for old-style MVC projects. Everything: razor pages, routing, configuration, DI, etc. is different on .NET Core. It's a complete rewrite of your application. This tool will try and reject these web projects if the appropriate ProjectTypeGuid is in the project file, but if that's missing then it may convert the project file. However, there's a ton of work cut out to actually getting the project to .NET Core when compared with other frameworks like WPF or WinForms. I recommend looking at articles like this: https://docs.microsoft.com/en-us/aspnet/core/migration/webapi?view=aspnetcore-3.1

**Comment by leonardochaia** [comment]
Hi, sorry to hijack this issue..
I've been using this to upgrade csproj files from the old format to the new sdk style, despite of .Net Core migration.

I have used this to only change the csproj, and have kept the target framework to net4x since that's my current situation, but allows me to target multiple frameworks like 461 and 472 and also keep a more sane csproj file in the meantime.

Is there any reason why we cant use this tool to migrate to the new csproj style instead of .Net Core? consider it an intermediate step.
If so, wouldn't it make sense to remove or allow removing through a CLI flag this check?

Perhaps i'm missing something. Thank you.

**Comment by jmarolf** [comment]
@leonardochaia you should be able to pass `--keep-current-tfms` to get what you want

https://github.com/dotnet/try-convert/blob/6b29b4c6f7898fd4476060bd428cb06497e73cb7/src/try-convert/Program.cs#L39

**Comment by cartermp** [comment]
Closing out old question
