### ISSUE TITLE
try-convert does not update app.config

### ISSUE THREAD

**Issue by docfresh** [dotnet/try-convert#296]
Try-convert does not seem to update app.config completely. This remnant remained in my project's app.config when I used try-convert to convert it to .NET Core 3.1

```
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
```

As a result, I kept getting an error when I tried to add a Settings file to the project and saving it.

"An error occurred while reading the app. config file. The file might be corrupted or contain invalid XML" 

The issue did not resolve until I deleted app.config and remade the settings file.

**Comment by cartermp** [comment]
@docfresh the tool will remove it as an Item include in your project file, but it doesn't delete the App.config file. I suspect this is just the VS tooling for adding a settings file that checks for the presence of an App.config on disk rather than checking if it's actually a part of the project. I think we can emit a message about finding one, letting you know that you need to delete this and move runtime configuration to a appsettings.json file.
