### ISSUE TITLE
process completed but project still on .net framework

### ISSUE THREAD

**Issue by AlterX76** [dotnet/try-convert#311]
I run the the application with the -w solution filename (and tried also only a project), although process is completed successfully, opening it in VS does not bring any change: framework is still .net 4.8, there are many removes from the project but nothing regarding .net core.
Is there a magic to have it working?

**Comment by cartermp** [comment]
Hello, we'll need more information. What was the project you ran this on? Can you share it? If not, can you share a similar repro? What version of try-convert are you using?

**Comment by AlterX76** [comment]
Hi, thanks for helping...
so as described in the doc, I cloned the project and installed it. The project I used as target for the conversion is really a normal C# library project based on .net framework 4.8
What I did not get is what this tool will give out as result; will it create a new project/solution with all required changes (in the project and source code) or it will only translate in the source code the APIs?
Because as I said, comparing the new project and the old one I just see many removals and opening the new project and compiling it, it just create the same binary as before just putting it in a net48 directory.

**Comment by cartermp** [comment]
Hmm. Sorry but I don't quite understand what you're referring to or trying to do here.

> so as described in the doc

Which document are you referring to?

> I cloned the project and installed it

Did you clone this project and run it from VS? Or did you install the .NET global tool?

> What I did not get is what this tool will give out as result; will it create a new project/solution with all required changes (in the project and source code) or it will only translate in the source code the APIs?

The `try-convert` tool will convert your project file, that's it. The goal is to make this aspect of migrating to .NET Core easy and convenient. From there, you need to deal with API differences yourself. There are several APIs on .NET Framework that are not available on .NET Core and you need to figure out how to migrate those yourself. In some cases there is no direct alternative and it may require doing something like pulling in a different package to solve a problem a different way.

**Comment by Nirmal4G** [comment]
@AlterX76

That's the point of this tool. It only converts the projects files to sdk-style/dialect/schema.

> Think of it like a C# refactoring where you convert a C# 5 to C# 8 dialect (_e.g.: convert a property with a backing field to auto-property or convert a bunch of if/else statements to switch or remove and sort the using statements or using Async/Await_).

<details>
<summary>What is an [Sdk-style project](https://docs.microsoft.com/dotnet/core/project-sdk/overview)?</summary>

The new Sdk-style projects has similar defaults like the old projects had but instead of writing those on every project file making it messy (_and not friendly with tools like git_) these were written to a shared set of common props/targets into a sdk pack and distributed via NuGet Gallery/dotnet sdk installer.

One of the main sdk pack that supports building basic .NET Core/Framework apps and libs is `Microsoft.NET.Sdk`. It extends common props/targets (_that already ship with MSBuild_) to provide sensible defaults (_i.e. auto include sources_), .NET Core support, new ProjectReference (_Project to Project_), new PackageReference (_Project to NuGet Package_) and much more. Thus greatly simplifying the project files.

You can read more about [it here](https://docs.microsoft.com/dotnet/core/project-sdk/overview).

</details>

**Comment by cartermp** [comment]
Closing due to no further info
